var groups = {
    "archiGrad": {
        "1": [
            "./extra/day2.png",
            "content/group_2/1/day2/processed/ed_ApaNsAhLoF_pr.png",
            "content/group_2/1/day2/processed/ed_DGfdjiGDTS_pr.png",
            "content/group_2/1/day2/processed/ed_DcSVbMlDsg_pr.png",
            "content/group_2/1/day2/processed/ed_FHkZiwpoOI_pr.png",
            "content/group_2/1/day2/processed/ed_FtGyaljkhb_pr.png",
            "content/group_2/1/day2/processed/ed_GeLXKrdBzY_pr.png",
            "content/group_2/1/day2/processed/ed_GtRZxtkovw_pr.png",
            "content/group_2/1/day2/processed/ed_HFiRdTYdCZ_pr.png",
            "content/group_2/1/day2/processed/ed_IEBDkZhuvJ_pr.png",
            "content/group_2/1/day2/processed/ed_IWBNLVhkEB_pr.png",
            "content/group_2/1/day2/processed/ed_JGfFjsgeox_pr.png",
            "content/group_2/1/day2/processed/ed_JXUmFczLWN_pr.png",
            "content/group_2/1/day2/processed/ed_KfCkkztqdM_pr.png",
            "content/group_2/1/day2/processed/ed_LXppjggvZU_pr.png",
            "content/group_2/1/day2/processed/ed_LlPsFmBsrD_pr.png",
            "content/group_2/1/day2/processed/ed_OApoUkZasc_pr.png",
            "content/group_2/1/day2/processed/ed_OrAZWhsXJo_pr.png",
            "content/group_2/1/day2/processed/ed_QGHRSqpplR_pr.png",
            "content/group_2/1/day2/processed/ed_QPQSWfuSBu_pr.png",
            "content/group_2/1/day2/processed/ed_QdqrqUhenn_pr.png",
            "content/group_2/1/day2/processed/ed_RDmMgIpTrf_pr.png",
            "content/group_2/1/day2/processed/ed_SQNZdGcxRm_pr.png",
            "content/group_2/1/day2/processed/ed_SttjyvgWUl_pr.png",
            "content/group_2/1/day2/processed/ed_SxgyFJhAmH_pr.png",
            "content/group_2/1/day2/processed/ed_UYYDTpPyYk_pr.png",
            "content/group_2/1/day2/processed/ed_YIguPJCBYB_pr.png",
            "content/group_2/1/day2/processed/ed_cNFYAgYUte_pr.png",
            "content/group_2/1/day2/processed/ed_cpcRZAqzfB_pr.png",
            "content/group_2/1/day2/processed/ed_dgUJrMexvZ_pr.png",
            "content/group_2/1/day2/processed/ed_dkupWldNtt_pr.png",
            "content/group_2/1/day2/processed/ed_dqziPHAkLP_pr.png",
            "content/group_2/1/day2/processed/ed_eUlkZkruzo_pr.png",
            "content/group_2/1/day2/processed/ed_gDEhLYsGtT_pr.png",
            "content/group_2/1/day2/processed/ed_gtAsgHoDnQ_pr.png",
            "content/group_2/1/day2/processed/ed_hjiTHIdoIl_pr.png",
            "content/group_2/1/day2/processed/ed_ikpifbOyQZ_pr.png",
            "content/group_2/1/day2/processed/ed_mgAomhZLhn_pr.png",
            "content/group_2/1/day2/processed/ed_mtrqdQdKNH_pr.png",
            "content/group_2/1/day2/processed/ed_sZGOXHNjDi_pr.png",
            "content/group_2/1/day2/processed/ed_uvVpnQtWHZ_pr.png",
            "content/group_2/1/day2/processed/ed_wEuscbzgNW_pr.png",
            "./extra/foo_day2.png",
            "content/group_2/1/day2/processed/1__MtupYutKAm_pr.png",
            "content/group_2/1/day2/processed/2__DHCstoqtkC_pr.png",
            "content/group_2/1/day2/processed/3__XaFigjPWfs_pr.png",
            "content/group_2/1/day2/processed/4__BUiknuuBkE_pr.png",
            "content/group_2/1/day2/processed/5__kBDwafjDAW_pr.png",
            "content/group_2/1/day2/processed/6__trMtnXFmxs_pr.png",
            "content/group_2/1/day2/processed/7__jFFBxgiyHQ_pr.png",
            "content/group_2/1/day2/processed/8__AuncpzAKOp_pr.png",
            "content/group_2/1/day2/processed/9__ftfoxOfYIP_pr.png",
            "content/group_2/1/day2/processed/10_eHVgcScfdq_pr.png",
            "content/group_2/1/day2/processed/11_NTcueuXRFg_pr.png",
            "content/group_2/1/day2/processed/12_QSQhXWVbZL_pr.png",
            "content/group_2/1/day2/processed/13_gudSiOspSi_pr.png",
            "./extra/ref_day2.png",
            "./extra/day_1.png",
            "./extra/foo_day_1.png",
            "content/group_2/1/day_1/processed/1__QuypjztZIS_pr.png",
            "content/group_2/1/day_1/processed/2__kwCDjURnqR_pr.png",
            "content/group_2/1/day_1/processed/3__tCiwrgxbnC_pr.png",
            "content/group_2/1/day_1/processed/4__BJBrDIhdtc_pr.png",
            "content/group_2/1/day_1/processed/5__sYGuiPQvFS_pr.png",
            "content/group_2/1/day_1/processed/6__AgWUIMdJhC_pr.png",
            "content/group_2/1/day_1/processed/7__qlALqvbRzW_pr.png",
            "content/group_2/1/day_1/processed/8__IYamYgdisd.gif_preProcessed_long_.png",
            "content/group_2/1/day_1/processed/8__kaTIBMLsUE_pr.png",
            "content/group_2/1/day_1/processed/9__HobennLiuj_pr.png",
            "content/group_2/1/day_1/processed/10_bKxbxACLrk_pr.png",
            "content/group_2/1/day_1/processed/11_hIjXDbJucR_pr.png",
            "content/group_2/1/day_1/processed/12_LwtiRrAOhU_pr.png",
            "content/group_2/1/day_1/processed/13_aPcnUbnbCU_pr.png",
            "content/group_2/1/day_1/processed/14_dbULoKKNwa_pr.png",
            "content/group_2/1/day_1/processed/15_egUgiVAVnj_pr.png",
            "content/group_2/1/day_1/processed/16_bZNbMjyXkJ_pr.png",
            "content/group_2/1/day_1/processed/17_cpivorxWMp_pr.png",
            "content/group_2/1/day_1/processed/18_pHiZOIJgNZ_pr.png",
            "content/group_2/1/day_1/processed/19_EXZgyaGPiO_pr.png",
            "content/group_2/1/day_1/processed/20_ydNpWDVKmR_pr.png",
            "content/group_2/1/day_1/processed/21_gYrPDSGCVu_pr.png",
            "content/group_2/1/day_1/processed/22_jvzeClSdOL_pr.png",
            "content/group_2/1/day_1/processed/23_JSNgmeHpfr_pr.png",
            "content/group_2/1/day_1/processed/24_ugFyHTKjhD_pr.png",
            "content/group_2/1/day_1/processed/25_ApTYAcyZAv_pr.png",
            "content/group_2/1/day_1/processed/re_BywnbTMQUC_pr.png",
            "content/group_2/1/day_1/processed/re_IQidgEzkVR_pr.png",
            "content/group_2/1/day_1/processed/re_OpvpPRsIEl_pr.png",
            "content/group_2/1/day_1/processed/re_XfyqgVgvMz_pr.png",
            "content/group_2/1/day_1/processed/re_bwZniodBgi_pr.png",
            "content/group_2/1/day_1/processed/re_cugCusOenS_pr.png",
            "content/group_2/1/day_1/processed/re_kgrkqNUDYW_pr.png",
            "content/group_2/1/day_1/processed/re_khRmJENagV_pr.png",
            "content/group_2/1/day_1/processed/re_knxOMJuULS_pr.png",
            "content/group_2/1/day_1/processed/re_oFvEnbiFHT_pr.png",
            "content/group_2/1/day_1/processed/re_pkQNuYQDrj_pr.png",
            "./extra/ref_day_1.png"
        ],
        "222": [
            "./extra/day2.png",
            "content/group_2/222/day2/processed/re_HYLfSBxYWH_pr.png",
            "content/group_2/222/day2/processed/re_VOKQpSsncw_pr.png",
            "content/group_2/222/day2/processed/re_bSGyOMkDjx_pr.png",
            "content/group_2/222/day2/processed/re_gzNstkIPUu_pr.png",
            "content/group_2/222/day2/processed/re_hdYmVZlvfh_pr.png",
            "content/group_2/222/day2/processed/re_jyQOpxFMXc_pr.png",
            "content/group_2/222/day2/processed/re_qPQLMUemAr_pr.png",
            "content/group_2/222/day2/processed/re_stPXOAkKJz_pr.png",
            "content/group_2/222/day2/processed/re_wpnYcsaxBq_pr.png",
            "content/group_2/222/day2/processed/re_ydHVVJELDL_pr.png",
            "./extra/foo_day2.png",
            "./extra/ref_day2.png",
            "./extra/day_1.png",
            "./extra/foo_day_1.png",
            "content/group_2/222/day_1/processed/1__BmwXRoRiKm_pr.png",
            "content/group_2/222/day_1/processed/2__XDueRlJiAo_pr.png",
            "content/group_2/222/day_1/processed/3__ZTOfzpIjLi_pr.png",
            "content/group_2/222/day_1/processed/4__HgcGYGILOf_pr.png",
            "content/group_2/222/day_1/processed/5__nnPBpXCEAa_pr.png",
            "content/group_2/222/day_1/processed/6__pIjaRImWgM_pr.png",
            "content/group_2/222/day_1/processed/7__nKiIUYyjZc_pr.png",
            "content/group_2/222/day_1/processed/8__RqAAJcaNIe_pr.png",
            "content/group_2/222/day_1/processed/8__VeWACNCbnP.gif_preProcessed_long_.png",
            "content/group_2/222/day_1/processed/9__tuBinupltj_pr.png",
            "content/group_2/222/day_1/processed/10_bogDsjzVSS_pr.png",
            "content/group_2/222/day_1/processed/11_xVkWfLJLWD_pr.png",
            "content/group_2/222/day_1/processed/12_JaOFMuTJbb_pr.png",
            "content/group_2/222/day_1/processed/13_HDjKHEMNqP_pr.png",
            "content/group_2/222/day_1/processed/14_shMcHYSAyi_pr.png",
            "content/group_2/222/day_1/processed/15_KsyRUavasn_pr.png",
            "content/group_2/222/day_1/processed/16_iQRzqpAcCz_pr.png",
            "content/group_2/222/day_1/processed/17_pkpNdaafxT_pr.png",
            "content/group_2/222/day_1/processed/18_jwTrhpNpyp_pr.png",
            "content/group_2/222/day_1/processed/19_KkYfAeqrSl_pr.png",
            "content/group_2/222/day_1/processed/20_vHSJGeejkr_pr.png",
            "content/group_2/222/day_1/processed/21_HZjBpuxeED_pr.png",
            "content/group_2/222/day_1/processed/22_ImWWVOHpPU_pr.png",
            "content/group_2/222/day_1/processed/23_vWVhjRnkOS_pr.png",
            "content/group_2/222/day_1/processed/24_uTigqmzZHB_pr.png",
            "content/group_2/222/day_1/processed/25_XHECEzknbS_pr.png",
            "content/group_2/222/day_1/processed/re_OLZWtIgwbg_pr.png",
            "content/group_2/222/day_1/processed/re_SNmORheNDy_pr.png",
            "content/group_2/222/day_1/processed/re_TFaxDKlNvy_pr.png",
            "content/group_2/222/day_1/processed/re_TIOrQPYRgO_pr.png",
            "content/group_2/222/day_1/processed/re_UeLMDiasMC_pr.png",
            "content/group_2/222/day_1/processed/re_cjQRiyZsVU_pr.png",
            "content/group_2/222/day_1/processed/re_dFANVzpgzG_pr.png",
            "content/group_2/222/day_1/processed/re_hlUwSEgrOE_pr.png",
            "content/group_2/222/day_1/processed/re_iPqFfAeBzN_pr.png",
            "content/group_2/222/day_1/processed/re_thrTGQCHDN_pr.png",
            "content/group_2/222/day_1/processed/re_wHBVhjwRXi_pr.png",
            "./extra/ref_day_1.png"
        ],
        "joris putteneers": [
            "./extra/foo_u1.png",
            "content/group_1/joris putteneers/u1/processed/re_YAXtQDKrLY_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_dekBAqgCYK_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_mKVtJCYmVE_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_mOjIKctFFK_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_mOtiMkBdma_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_mmiDpVewWH_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_moiylxTdlb_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_mrnjWxmgUG_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_spytqzVYkh_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_uWjxprtxGg_pr.png",
            "./extra/ref_u1.png",
            "./extra/u2.png",
            "content/group_1/joris putteneers/u2/processed/re_BpCmESaypI_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_CMYzssEVlB_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_EWuEzNcejW_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_FxCcnNLFKY_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_GqsWqNhROl_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_HAVecKcdIQ_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_JTdkjuLUAm_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_KeEaWAhvvf_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_PtsORbWtrg_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_azdAWaYPKA_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_dVXUADoGgB_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_jmhODObnEt_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_nFBkAYUkwG_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_pQWfdAEDwW_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_rbqWGCaeWL_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_wfyNnlwIHI_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_xLOidqoVyd_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_xVbVRhWudA_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_xjzgdWcKnG_pr.png",
            "./extra/foo_u2.png",
            "./extra/ref_u2.png"
        ],
        "nog ne keer he": [
            "./extra/foo_dd.png",
            "content/sad/nog ne keer he/dd/processed/re_SYFJMzmIxH_pr.png",
            "content/sad/nog ne keer he/dd/processed/re_zhKhIHqhYi_pr.png",
            "./extra/ref_dd.png"
        ],
        "sdf": [
            "./extra/foo_dd.png",
            "content/sad/sdf/dd/processed/re_RFzVvDsJlu_pr.png",
            "content/sad/sdf/dd/processed/re_tkxLJvLHHG_pr.png",
            "./extra/ref_dd.png"
        ],
        "\u0e01\u0e02\u0e03\u0e04\u0e05\u0e06\u0e07\u0e08\u0e09\u0e0a\u0e0b\u0e0c\u0e0d\u0e0e\u0e0f\u0e10\u0e11\u0e12\u0e13\u0e14\u0e15\u0e16\u0e17\u0e18\u0e19\u0e1a\u0e1b\u0e1c\u0e1d\u0e1e\u0e1f\u0e20\u0e21\u0e22\u0e23\u0e24\u0e25\u0e27\u0e28\u0e29\u0e2a\u0e2b\u0e2c\u0e2d\u0e2e": [
            "./extra/foo_dd.png",
            "content/sad/\u0e01\u0e02\u0e03\u0e04\u0e05\u0e06\u0e07\u0e08\u0e09\u0e0a\u0e0b\u0e0c\u0e0d\u0e0e\u0e0f\u0e10\u0e11\u0e12\u0e13\u0e14\u0e15\u0e16\u0e17\u0e18\u0e19\u0e1a\u0e1b\u0e1c\u0e1d\u0e1e\u0e1f\u0e20\u0e21\u0e22\u0e23\u0e24\u0e25\u0e27\u0e28\u0e29\u0e2a\u0e2b\u0e2c\u0e2d\u0e2e/dd/processed/re_OpMEkSwgjI_pr.png",
            "content/sad/\u0e01\u0e02\u0e03\u0e04\u0e05\u0e06\u0e07\u0e08\u0e09\u0e0a\u0e0b\u0e0c\u0e0d\u0e0e\u0e0f\u0e10\u0e11\u0e12\u0e13\u0e14\u0e15\u0e16\u0e17\u0e18\u0e19\u0e1a\u0e1b\u0e1c\u0e1d\u0e1e\u0e1f\u0e20\u0e21\u0e22\u0e23\u0e24\u0e25\u0e27\u0e28\u0e29\u0e2a\u0e2b\u0e2c\u0e2d\u0e2e/dd/processed/re_yJRzhvfbFD_pr.png",
            "./extra/ref_dd.png"
        ],
        "q": [
            "./extra/ee.png",
            "content/sdf/q/ee/processed/re_NvkOuwSDlR_pr.png",
            "content/sdf/q/ee/processed/re_TCJVJxncXT_pr.png",
            "content/sdf/q/ee/processed/re_ZNboeXOrMc_pr.png",
            "content/sdf/q/ee/processed/re_dAjRYOFKgL_pr.png",
            "content/sdf/q/ee/processed/re_gMgEUbsITn_pr.png",
            "content/sdf/q/ee/processed/re_hXZKgMVsaD_pr.png",
            "content/sdf/q/ee/processed/re_jLafNgCXHH_pr.png",
            "./extra/foo_ee.png",
            "./extra/ref_ee.png"
        ],
        "ss": [
            "./extra/asd.png",
            "content/ssdsd/ss/asd/processed/ed_GhpWeRmVPU_pr.png",
            "content/ssdsd/ss/asd/processed/ed_MZZIXoDXyq_pr.png",
            "content/ssdsd/ss/asd/processed/ed_PGdxcVDUyz_pr.png",
            "content/ssdsd/ss/asd/processed/ed_PPQzcyQdPY_pr.png",
            "content/ssdsd/ss/asd/processed/ed_QUVFNOFRue_pr.png",
            "content/ssdsd/ss/asd/processed/ed_SqHyyOgzod_pr.png",
            "content/ssdsd/ss/asd/processed/ed_SxPzNQoTEl_pr.png",
            "content/ssdsd/ss/asd/processed/ed_VpLiayYQdl_pr.png",
            "content/ssdsd/ss/asd/processed/ed_YTAACDsImA_pr.png",
            "content/ssdsd/ss/asd/processed/ed_hrnkeXyqPM_pr.png",
            "content/ssdsd/ss/asd/processed/ed_kuiYeZaWbc_pr.png",
            "content/ssdsd/ss/asd/processed/ed_tIXMBshNuS_pr.png",
            "content/ssdsd/ss/asd/processed/ed_wtoKpqivWV_pr.png",
            "./extra/foo_asd.png",
            "content/ssdsd/ss/asd/processed/1__yGrYVZrOIO_pr.png",
            "content/ssdsd/ss/asd/processed/2__uKGdbizZhc_pr.png",
            "content/ssdsd/ss/asd/processed/3__czgFzMwAQk_pr.png",
            "content/ssdsd/ss/asd/processed/4__SGogMgoybO_pr.png",
            "content/ssdsd/ss/asd/processed/5__VMOXTAHsID_pr.png",
            "content/ssdsd/ss/asd/processed/6__DNrhoPipbh_pr.png",
            "content/ssdsd/ss/asd/processed/7__sSWxrvXVUA_pr.png",
            "content/ssdsd/ss/asd/processed/8__ahEHNcTknR_pr.png",
            "content/ssdsd/ss/asd/processed/9__UOvPYKWdcO_pr.png",
            "content/ssdsd/ss/asd/processed/10_DFLgsXsATK_pr.png",
            "content/ssdsd/ss/asd/processed/11_eIEBrJvsiR_pr.png",
            "content/ssdsd/ss/asd/processed/12_wlAkWRLDkc_pr.png",
            "content/ssdsd/ss/asd/processed/13_fVmMISiNHj_pr.png",
            "./extra/ref_asd.png"
        ],
        "ssdfdf": [
            "./extra/foo_ffs.png",
            "content/test/ssdfdf/ffs/processed/re_GMKCNwlBaZ_pr.png",
            "content/test/ssdfdf/ffs/processed/re_MyiMQHfCAU_pr.png",
            "content/test/ssdfdf/ffs/processed/re_RCVSXXgskL_pr.png",
            "content/test/ssdfdf/ffs/processed/re_XImgLrAOBu_pr.png",
            "content/test/ssdfdf/ffs/processed/re_bryqJTCDRW_pr.png",
            "content/test/ssdfdf/ffs/processed/re_rLRLOlPrnb_pr.png",
            "./extra/ref_ffs.png"
        ]
    },
    "ddsdaf": {
        "1": [
            "./extra/day2.png",
            "content/ddsdaf/1/day2/processed/ed_CxskCgGiDj_pr.png",
            "content/ddsdaf/1/day2/processed/ed_DZXmYTkEHf_pr.png",
            "content/ddsdaf/1/day2/processed/ed_DxNvPKPJvQ_pr.png",
            "content/ddsdaf/1/day2/processed/ed_GnQOuEIHAl_pr.png",
            "content/ddsdaf/1/day2/processed/ed_GzdYIRbDpj_pr.png",
            "content/ddsdaf/1/day2/processed/ed_IPxbWxXmvi_pr.png",
            "content/ddsdaf/1/day2/processed/ed_LDiwBBiAmR_pr.png",
            "content/ddsdaf/1/day2/processed/ed_MGXnkYBnOw_pr.png",
            "content/ddsdaf/1/day2/processed/ed_OFHuJdZAeS_pr.png",
            "content/ddsdaf/1/day2/processed/ed_OPnNhjFywC_pr.png",
            "content/ddsdaf/1/day2/processed/ed_ORdlpnaWJR_pr.png",
            "content/ddsdaf/1/day2/processed/ed_OgdJWsGjAA_pr.png",
            "content/ddsdaf/1/day2/processed/ed_PVaLSRqPov_pr.png",
            "content/ddsdaf/1/day2/processed/ed_PYTCTFBLIz_pr.png",
            "content/ddsdaf/1/day2/processed/ed_QcdyHCfxbH_pr.png",
            "content/ddsdaf/1/day2/processed/ed_WKuzBrBbQB_pr.png",
            "content/ddsdaf/1/day2/processed/ed_XQsRnntOSK_pr.png",
            "content/ddsdaf/1/day2/processed/ed_YMBVQIpFrr_pr.png",
            "content/ddsdaf/1/day2/processed/ed_ZVAqtRzXIv_pr.png",
            "content/ddsdaf/1/day2/processed/ed_aONiLWNsvq_pr.png",
            "content/ddsdaf/1/day2/processed/ed_bbInRdqfcl_pr.png",
            "content/ddsdaf/1/day2/processed/ed_dQNffcFGgk_pr.png",
            "content/ddsdaf/1/day2/processed/ed_ddyfWNgSFF_pr.png",
            "content/ddsdaf/1/day2/processed/ed_fYzxcSuIHv_pr.png",
            "content/ddsdaf/1/day2/processed/ed_lLRxMEhtMe_pr.png",
            "content/ddsdaf/1/day2/processed/ed_lVYYausfxC_pr.png",
            "content/ddsdaf/1/day2/processed/ed_mCfYEnvPQO_pr.png",
            "content/ddsdaf/1/day2/processed/ed_msooKbXfpr_pr.png",
            "content/ddsdaf/1/day2/processed/ed_nHVnFSvDnV_pr.png",
            "content/ddsdaf/1/day2/processed/ed_nXcWBNhSCa_pr.png",
            "content/ddsdaf/1/day2/processed/ed_pDuWNxIXKX_pr.png",
            "content/ddsdaf/1/day2/processed/ed_pzHeaSRtMd_pr.png",
            "content/ddsdaf/1/day2/processed/ed_rRrzeCZEHQ_pr.png",
            "content/ddsdaf/1/day2/processed/ed_rxtpuauhqu_pr.png",
            "content/ddsdaf/1/day2/processed/ed_ryRAqZHAzE_pr.png",
            "content/ddsdaf/1/day2/processed/ed_sSWCiKSBmz_pr.png",
            "content/ddsdaf/1/day2/processed/ed_sqzdhIemwI_pr.png",
            "content/ddsdaf/1/day2/processed/ed_tgKpuNiQLE_pr.png",
            "content/ddsdaf/1/day2/processed/ed_wxIozptYix_pr.png",
            "content/ddsdaf/1/day2/processed/ed_xJyBuUZmch_pr.png",
            "content/ddsdaf/1/day2/processed/ed_xUFmqmTUHe_pr.png",
            "./extra/foo_day2.png",
            "content/ddsdaf/1/day2/processed/1__KTsmZIdCZS_pr.png",
            "content/ddsdaf/1/day2/processed/2__bMeycKTyYB_pr.png",
            "content/ddsdaf/1/day2/processed/3__KlOMaWWkMe_pr.png",
            "content/ddsdaf/1/day2/processed/4__HPZgSQHozK_pr.png",
            "content/ddsdaf/1/day2/processed/5__OeokQZlRLl_pr.png",
            "content/ddsdaf/1/day2/processed/6__fSSFUGipEs_pr.png",
            "content/ddsdaf/1/day2/processed/7__QHRsbWJlyZ_pr.png",
            "content/ddsdaf/1/day2/processed/8__lOSpROrUEw_pr.png",
            "content/ddsdaf/1/day2/processed/9__NsJiAtMkgu_pr.png",
            "content/ddsdaf/1/day2/processed/10_zYDgzLmnho_pr.png",
            "content/ddsdaf/1/day2/processed/11_IZWsVlpqfN_pr.png",
            "content/ddsdaf/1/day2/processed/12_qgMuJyCytr_pr.png",
            "content/ddsdaf/1/day2/processed/13_FYoIXgPWnd_pr.png",
            "./extra/ref_day2.png",
            "./extra/day_1.png",
            "./extra/foo_day_1.png",
            "content/ddsdaf/1/day_1/processed/1__ZXiERtjCge_pr.png",
            "content/ddsdaf/1/day_1/processed/2__aDOXBnmmHW_pr.png",
            "content/ddsdaf/1/day_1/processed/3__gLfjFRIMIy_pr.png",
            "content/ddsdaf/1/day_1/processed/4__CUwYLZNJtH_pr.png",
            "content/ddsdaf/1/day_1/processed/5__QpenEXlZRd_pr.png",
            "content/ddsdaf/1/day_1/processed/6__MjCOmmRUsJ_pr.png",
            "content/ddsdaf/1/day_1/processed/7__gLzibfcOoJ_pr.png",
            "content/ddsdaf/1/day_1/processed/8__TKgPRCOorj_pr.png",
            "content/ddsdaf/1/day_1/processed/8__sovRpAKwoc.gif_preProcessed_long_.png",
            "content/ddsdaf/1/day_1/processed/9__pWuaPlPwzq_pr.png",
            "content/ddsdaf/1/day_1/processed/10_rhLyLZwglE_pr.png",
            "content/ddsdaf/1/day_1/processed/11_thsSjTLDMe_pr.png",
            "content/ddsdaf/1/day_1/processed/12_UaukFIKNCR_pr.png",
            "content/ddsdaf/1/day_1/processed/13_ztJMeQfBKC_pr.png",
            "content/ddsdaf/1/day_1/processed/14_xHtxtbPRWm_pr.png",
            "content/ddsdaf/1/day_1/processed/15_GPawCVSCNq_pr.png",
            "content/ddsdaf/1/day_1/processed/16_cyTpZYePeZ_pr.png",
            "content/ddsdaf/1/day_1/processed/17_ziYeYlGNep_pr.png",
            "content/ddsdaf/1/day_1/processed/18_ykbmZBKhIN_pr.png",
            "content/ddsdaf/1/day_1/processed/19_XWhgEFZwXS_pr.png",
            "content/ddsdaf/1/day_1/processed/20_WJedOZcEbm_pr.png",
            "content/ddsdaf/1/day_1/processed/21_TgibazgYQO_pr.png",
            "content/ddsdaf/1/day_1/processed/22_AQvOrVmtNT_pr.png",
            "content/ddsdaf/1/day_1/processed/23_WDAxsMQFnA_pr.png",
            "content/ddsdaf/1/day_1/processed/24_gyOZxqOrfH_pr.png",
            "content/ddsdaf/1/day_1/processed/25_vycnBgPmQn_pr.png",
            "content/ddsdaf/1/day_1/processed/re_EleeLgmOMc_pr.png",
            "content/ddsdaf/1/day_1/processed/re_HieHtLyuIf_pr.png",
            "content/ddsdaf/1/day_1/processed/re_IhwTZstqLT_pr.png",
            "content/ddsdaf/1/day_1/processed/re_JhhqXKlDwx_pr.png",
            "content/ddsdaf/1/day_1/processed/re_ReMjpeQlar_pr.png",
            "content/ddsdaf/1/day_1/processed/re_WSuAOghTuA_pr.png",
            "content/ddsdaf/1/day_1/processed/re_dBFkbktXSM_pr.png",
            "content/ddsdaf/1/day_1/processed/re_jsSaExeLkY_pr.png",
            "content/ddsdaf/1/day_1/processed/re_tPHAgTxyvk_pr.png",
            "content/ddsdaf/1/day_1/processed/re_tVkGqDRBuK_pr.png",
            "content/ddsdaf/1/day_1/processed/re_uYlYErhZHb_pr.png",
            "./extra/ref_day_1.png"
        ],
        "222": [
            "./extra/day2.png",
            "content/ddsdaf/222/day2/processed/re_ATNOytjlFE_pr.png",
            "content/ddsdaf/222/day2/processed/re_BPZDsxRnRI_pr.png",
            "content/ddsdaf/222/day2/processed/re_EEZXLnzsbl_pr.png",
            "content/ddsdaf/222/day2/processed/re_SUAdpYrpIJ_pr.png",
            "content/ddsdaf/222/day2/processed/re_SYMhjjFcuH_pr.png",
            "content/ddsdaf/222/day2/processed/re_mFthvrGFoJ_pr.png",
            "content/ddsdaf/222/day2/processed/re_oTkhEdlTwJ_pr.png",
            "content/ddsdaf/222/day2/processed/re_sCCTgzQMjD_pr.png",
            "content/ddsdaf/222/day2/processed/re_uOFcLTDgKw_pr.png",
            "content/ddsdaf/222/day2/processed/re_zfpLYJUybM_pr.png",
            "./extra/foo_day2.png",
            "./extra/ref_day2.png",
            "./extra/day_1.png",
            "./extra/foo_day_1.png",
            "content/ddsdaf/222/day_1/processed/1__PVCDbACMWk_pr.png",
            "content/ddsdaf/222/day_1/processed/2__WZuwhAkoHJ_pr.png",
            "content/ddsdaf/222/day_1/processed/3__cfmnzRBGFT_pr.png",
            "content/ddsdaf/222/day_1/processed/4__SkbvkeXSSp_pr.png",
            "content/ddsdaf/222/day_1/processed/5__arqwuutVsd_pr.png",
            "content/ddsdaf/222/day_1/processed/6__vuttrZzHjt_pr.png",
            "content/ddsdaf/222/day_1/processed/7__UJvALTFMxp_pr.png",
            "content/ddsdaf/222/day_1/processed/8__EPxWgGzFqs_pr.png",
            "content/ddsdaf/222/day_1/processed/8__KJycyxakLG.gif_preProcessed_long_.png",
            "content/ddsdaf/222/day_1/processed/9__PTrFlQcnBD_pr.png",
            "content/ddsdaf/222/day_1/processed/10_prMhHTHOsf_pr.png",
            "content/ddsdaf/222/day_1/processed/11_iyefudhSaV_pr.png",
            "content/ddsdaf/222/day_1/processed/12_GqTeZdaHNr_pr.png",
            "content/ddsdaf/222/day_1/processed/13_kMiivzOFTG_pr.png",
            "content/ddsdaf/222/day_1/processed/14_hAYavaUtph_pr.png",
            "content/ddsdaf/222/day_1/processed/15_aLaaVOkUEI_pr.png",
            "content/ddsdaf/222/day_1/processed/16_kQeTwycHpI_pr.png",
            "content/ddsdaf/222/day_1/processed/17_SsuQcbWdTA_pr.png",
            "content/ddsdaf/222/day_1/processed/18_olGngdJTGV_pr.png",
            "content/ddsdaf/222/day_1/processed/19_zSXThUaAQD_pr.png",
            "content/ddsdaf/222/day_1/processed/20_zJNqhBLrlN_pr.png",
            "content/ddsdaf/222/day_1/processed/21_qKRnwQJmVW_pr.png",
            "content/ddsdaf/222/day_1/processed/22_IGLTajKjqI_pr.png",
            "content/ddsdaf/222/day_1/processed/23_usSfaUfTDB_pr.png",
            "content/ddsdaf/222/day_1/processed/24_FCsirKvGbA_pr.png",
            "content/ddsdaf/222/day_1/processed/25_gqDjIznCTT_pr.png",
            "content/ddsdaf/222/day_1/processed/re_GjizhoUauR_pr.png",
            "content/ddsdaf/222/day_1/processed/re_JjQeZUSTut_pr.png",
            "content/ddsdaf/222/day_1/processed/re_OTwfWWYyHS_pr.png",
            "content/ddsdaf/222/day_1/processed/re_PVtIKPmQgB_pr.png",
            "content/ddsdaf/222/day_1/processed/re_VKqbtUOxkW_pr.png",
            "content/ddsdaf/222/day_1/processed/re_dXMBCAlRRF_pr.png",
            "content/ddsdaf/222/day_1/processed/re_efMFvBfZIu_pr.png",
            "content/ddsdaf/222/day_1/processed/re_ilmbGEtHPN_pr.png",
            "content/ddsdaf/222/day_1/processed/re_lCGRlovTij_pr.png",
            "content/ddsdaf/222/day_1/processed/re_wlhkVzNiCp_pr.png",
            "content/ddsdaf/222/day_1/processed/re_zbPmRcLEYV_pr.png",
            "./extra/ref_day_1.png"
        ]
    },
    "group_1": {
        "joris putteneers": [
            "./extra/foo_u1.png",
            "content/group_1/joris putteneers/u1/processed/re_YAXtQDKrLY_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_dekBAqgCYK_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_mKVtJCYmVE_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_mOjIKctFFK_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_mOtiMkBdma_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_mmiDpVewWH_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_moiylxTdlb_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_mrnjWxmgUG_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_spytqzVYkh_pr.png",
            "content/group_1/joris putteneers/u1/processed/re_uWjxprtxGg_pr.png",
            "./extra/ref_u1.png",
            "./extra/u2.png",
            "content/group_1/joris putteneers/u2/processed/re_BpCmESaypI_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_CMYzssEVlB_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_EWuEzNcejW_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_FxCcnNLFKY_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_GqsWqNhROl_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_HAVecKcdIQ_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_JTdkjuLUAm_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_KeEaWAhvvf_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_PtsORbWtrg_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_azdAWaYPKA_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_dVXUADoGgB_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_jmhODObnEt_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_nFBkAYUkwG_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_pQWfdAEDwW_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_rbqWGCaeWL_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_wfyNnlwIHI_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_xLOidqoVyd_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_xVbVRhWudA_pr.png",
            "content/group_1/joris putteneers/u2/processed/re_xjzgdWcKnG_pr.png",
            "./extra/foo_u2.png",
            "./extra/ref_u2.png"
        ]
    },
    "group_2": {
        "1": [
            "./extra/day2.png",
            "content/group_2/1/day2/processed/ed_ApaNsAhLoF_pr.png",
            "content/group_2/1/day2/processed/ed_DGfdjiGDTS_pr.png",
            "content/group_2/1/day2/processed/ed_DcSVbMlDsg_pr.png",
            "content/group_2/1/day2/processed/ed_FHkZiwpoOI_pr.png",
            "content/group_2/1/day2/processed/ed_FtGyaljkhb_pr.png",
            "content/group_2/1/day2/processed/ed_GeLXKrdBzY_pr.png",
            "content/group_2/1/day2/processed/ed_GtRZxtkovw_pr.png",
            "content/group_2/1/day2/processed/ed_HFiRdTYdCZ_pr.png",
            "content/group_2/1/day2/processed/ed_IEBDkZhuvJ_pr.png",
            "content/group_2/1/day2/processed/ed_IWBNLVhkEB_pr.png",
            "content/group_2/1/day2/processed/ed_JGfFjsgeox_pr.png",
            "content/group_2/1/day2/processed/ed_JXUmFczLWN_pr.png",
            "content/group_2/1/day2/processed/ed_KfCkkztqdM_pr.png",
            "content/group_2/1/day2/processed/ed_LXppjggvZU_pr.png",
            "content/group_2/1/day2/processed/ed_LlPsFmBsrD_pr.png",
            "content/group_2/1/day2/processed/ed_OApoUkZasc_pr.png",
            "content/group_2/1/day2/processed/ed_OrAZWhsXJo_pr.png",
            "content/group_2/1/day2/processed/ed_QGHRSqpplR_pr.png",
            "content/group_2/1/day2/processed/ed_QPQSWfuSBu_pr.png",
            "content/group_2/1/day2/processed/ed_QdqrqUhenn_pr.png",
            "content/group_2/1/day2/processed/ed_RDmMgIpTrf_pr.png",
            "content/group_2/1/day2/processed/ed_SQNZdGcxRm_pr.png",
            "content/group_2/1/day2/processed/ed_SttjyvgWUl_pr.png",
            "content/group_2/1/day2/processed/ed_SxgyFJhAmH_pr.png",
            "content/group_2/1/day2/processed/ed_UYYDTpPyYk_pr.png",
            "content/group_2/1/day2/processed/ed_YIguPJCBYB_pr.png",
            "content/group_2/1/day2/processed/ed_cNFYAgYUte_pr.png",
            "content/group_2/1/day2/processed/ed_cpcRZAqzfB_pr.png",
            "content/group_2/1/day2/processed/ed_dgUJrMexvZ_pr.png",
            "content/group_2/1/day2/processed/ed_dkupWldNtt_pr.png",
            "content/group_2/1/day2/processed/ed_dqziPHAkLP_pr.png",
            "content/group_2/1/day2/processed/ed_eUlkZkruzo_pr.png",
            "content/group_2/1/day2/processed/ed_gDEhLYsGtT_pr.png",
            "content/group_2/1/day2/processed/ed_gtAsgHoDnQ_pr.png",
            "content/group_2/1/day2/processed/ed_hjiTHIdoIl_pr.png",
            "content/group_2/1/day2/processed/ed_ikpifbOyQZ_pr.png",
            "content/group_2/1/day2/processed/ed_mgAomhZLhn_pr.png",
            "content/group_2/1/day2/processed/ed_mtrqdQdKNH_pr.png",
            "content/group_2/1/day2/processed/ed_sZGOXHNjDi_pr.png",
            "content/group_2/1/day2/processed/ed_uvVpnQtWHZ_pr.png",
            "content/group_2/1/day2/processed/ed_wEuscbzgNW_pr.png",
            "./extra/foo_day2.png",
            "content/group_2/1/day2/processed/1__MtupYutKAm_pr.png",
            "content/group_2/1/day2/processed/2__DHCstoqtkC_pr.png",
            "content/group_2/1/day2/processed/3__XaFigjPWfs_pr.png",
            "content/group_2/1/day2/processed/4__BUiknuuBkE_pr.png",
            "content/group_2/1/day2/processed/5__kBDwafjDAW_pr.png",
            "content/group_2/1/day2/processed/6__trMtnXFmxs_pr.png",
            "content/group_2/1/day2/processed/7__jFFBxgiyHQ_pr.png",
            "content/group_2/1/day2/processed/8__AuncpzAKOp_pr.png",
            "content/group_2/1/day2/processed/9__ftfoxOfYIP_pr.png",
            "content/group_2/1/day2/processed/10_eHVgcScfdq_pr.png",
            "content/group_2/1/day2/processed/11_NTcueuXRFg_pr.png",
            "content/group_2/1/day2/processed/12_QSQhXWVbZL_pr.png",
            "content/group_2/1/day2/processed/13_gudSiOspSi_pr.png",
            "./extra/ref_day2.png",
            "./extra/day_1.png",
            "./extra/foo_day_1.png",
            "content/group_2/1/day_1/processed/1__QuypjztZIS_pr.png",
            "content/group_2/1/day_1/processed/2__kwCDjURnqR_pr.png",
            "content/group_2/1/day_1/processed/3__tCiwrgxbnC_pr.png",
            "content/group_2/1/day_1/processed/4__BJBrDIhdtc_pr.png",
            "content/group_2/1/day_1/processed/5__sYGuiPQvFS_pr.png",
            "content/group_2/1/day_1/processed/6__AgWUIMdJhC_pr.png",
            "content/group_2/1/day_1/processed/7__qlALqvbRzW_pr.png",
            "content/group_2/1/day_1/processed/8__IYamYgdisd.gif_preProcessed_long_.png",
            "content/group_2/1/day_1/processed/8__kaTIBMLsUE_pr.png",
            "content/group_2/1/day_1/processed/9__HobennLiuj_pr.png",
            "content/group_2/1/day_1/processed/10_bKxbxACLrk_pr.png",
            "content/group_2/1/day_1/processed/11_hIjXDbJucR_pr.png",
            "content/group_2/1/day_1/processed/12_LwtiRrAOhU_pr.png",
            "content/group_2/1/day_1/processed/13_aPcnUbnbCU_pr.png",
            "content/group_2/1/day_1/processed/14_dbULoKKNwa_pr.png",
            "content/group_2/1/day_1/processed/15_egUgiVAVnj_pr.png",
            "content/group_2/1/day_1/processed/16_bZNbMjyXkJ_pr.png",
            "content/group_2/1/day_1/processed/17_cpivorxWMp_pr.png",
            "content/group_2/1/day_1/processed/18_pHiZOIJgNZ_pr.png",
            "content/group_2/1/day_1/processed/19_EXZgyaGPiO_pr.png",
            "content/group_2/1/day_1/processed/20_ydNpWDVKmR_pr.png",
            "content/group_2/1/day_1/processed/21_gYrPDSGCVu_pr.png",
            "content/group_2/1/day_1/processed/22_jvzeClSdOL_pr.png",
            "content/group_2/1/day_1/processed/23_JSNgmeHpfr_pr.png",
            "content/group_2/1/day_1/processed/24_ugFyHTKjhD_pr.png",
            "content/group_2/1/day_1/processed/25_ApTYAcyZAv_pr.png",
            "content/group_2/1/day_1/processed/re_BywnbTMQUC_pr.png",
            "content/group_2/1/day_1/processed/re_IQidgEzkVR_pr.png",
            "content/group_2/1/day_1/processed/re_OpvpPRsIEl_pr.png",
            "content/group_2/1/day_1/processed/re_XfyqgVgvMz_pr.png",
            "content/group_2/1/day_1/processed/re_bwZniodBgi_pr.png",
            "content/group_2/1/day_1/processed/re_cugCusOenS_pr.png",
            "content/group_2/1/day_1/processed/re_kgrkqNUDYW_pr.png",
            "content/group_2/1/day_1/processed/re_khRmJENagV_pr.png",
            "content/group_2/1/day_1/processed/re_knxOMJuULS_pr.png",
            "content/group_2/1/day_1/processed/re_oFvEnbiFHT_pr.png",
            "content/group_2/1/day_1/processed/re_pkQNuYQDrj_pr.png",
            "./extra/ref_day_1.png"
        ],
        "222": [
            "./extra/day2.png",
            "content/group_2/222/day2/processed/re_HYLfSBxYWH_pr.png",
            "content/group_2/222/day2/processed/re_VOKQpSsncw_pr.png",
            "content/group_2/222/day2/processed/re_bSGyOMkDjx_pr.png",
            "content/group_2/222/day2/processed/re_gzNstkIPUu_pr.png",
            "content/group_2/222/day2/processed/re_hdYmVZlvfh_pr.png",
            "content/group_2/222/day2/processed/re_jyQOpxFMXc_pr.png",
            "content/group_2/222/day2/processed/re_qPQLMUemAr_pr.png",
            "content/group_2/222/day2/processed/re_stPXOAkKJz_pr.png",
            "content/group_2/222/day2/processed/re_wpnYcsaxBq_pr.png",
            "content/group_2/222/day2/processed/re_ydHVVJELDL_pr.png",
            "./extra/foo_day2.png",
            "./extra/ref_day2.png",
            "./extra/day_1.png",
            "./extra/foo_day_1.png",
            "content/group_2/222/day_1/processed/1__BmwXRoRiKm_pr.png",
            "content/group_2/222/day_1/processed/2__XDueRlJiAo_pr.png",
            "content/group_2/222/day_1/processed/3__ZTOfzpIjLi_pr.png",
            "content/group_2/222/day_1/processed/4__HgcGYGILOf_pr.png",
            "content/group_2/222/day_1/processed/5__nnPBpXCEAa_pr.png",
            "content/group_2/222/day_1/processed/6__pIjaRImWgM_pr.png",
            "content/group_2/222/day_1/processed/7__nKiIUYyjZc_pr.png",
            "content/group_2/222/day_1/processed/8__RqAAJcaNIe_pr.png",
            "content/group_2/222/day_1/processed/8__VeWACNCbnP.gif_preProcessed_long_.png",
            "content/group_2/222/day_1/processed/9__tuBinupltj_pr.png",
            "content/group_2/222/day_1/processed/10_bogDsjzVSS_pr.png",
            "content/group_2/222/day_1/processed/11_xVkWfLJLWD_pr.png",
            "content/group_2/222/day_1/processed/12_JaOFMuTJbb_pr.png",
            "content/group_2/222/day_1/processed/13_HDjKHEMNqP_pr.png",
            "content/group_2/222/day_1/processed/14_shMcHYSAyi_pr.png",
            "content/group_2/222/day_1/processed/15_KsyRUavasn_pr.png",
            "content/group_2/222/day_1/processed/16_iQRzqpAcCz_pr.png",
            "content/group_2/222/day_1/processed/17_pkpNdaafxT_pr.png",
            "content/group_2/222/day_1/processed/18_jwTrhpNpyp_pr.png",
            "content/group_2/222/day_1/processed/19_KkYfAeqrSl_pr.png",
            "content/group_2/222/day_1/processed/20_vHSJGeejkr_pr.png",
            "content/group_2/222/day_1/processed/21_HZjBpuxeED_pr.png",
            "content/group_2/222/day_1/processed/22_ImWWVOHpPU_pr.png",
            "content/group_2/222/day_1/processed/23_vWVhjRnkOS_pr.png",
            "content/group_2/222/day_1/processed/24_uTigqmzZHB_pr.png",
            "content/group_2/222/day_1/processed/25_XHECEzknbS_pr.png",
            "content/group_2/222/day_1/processed/re_OLZWtIgwbg_pr.png",
            "content/group_2/222/day_1/processed/re_SNmORheNDy_pr.png",
            "content/group_2/222/day_1/processed/re_TFaxDKlNvy_pr.png",
            "content/group_2/222/day_1/processed/re_TIOrQPYRgO_pr.png",
            "content/group_2/222/day_1/processed/re_UeLMDiasMC_pr.png",
            "content/group_2/222/day_1/processed/re_cjQRiyZsVU_pr.png",
            "content/group_2/222/day_1/processed/re_dFANVzpgzG_pr.png",
            "content/group_2/222/day_1/processed/re_hlUwSEgrOE_pr.png",
            "content/group_2/222/day_1/processed/re_iPqFfAeBzN_pr.png",
            "content/group_2/222/day_1/processed/re_thrTGQCHDN_pr.png",
            "content/group_2/222/day_1/processed/re_wHBVhjwRXi_pr.png",
            "./extra/ref_day_1.png"
        ]
    },
    "sad": {
        "nog ne keer he": [
            "./extra/foo_dd.png",
            "content/sad/nog ne keer he/dd/processed/re_SYFJMzmIxH_pr.png",
            "content/sad/nog ne keer he/dd/processed/re_zhKhIHqhYi_pr.png",
            "./extra/ref_dd.png"
        ],
        "sdf": [
            "./extra/foo_dd.png",
            "content/sad/sdf/dd/processed/re_RFzVvDsJlu_pr.png",
            "content/sad/sdf/dd/processed/re_tkxLJvLHHG_pr.png",
            "./extra/ref_dd.png"
        ],
        "\u0e01\u0e02\u0e03\u0e04\u0e05\u0e06\u0e07\u0e08\u0e09\u0e0a\u0e0b\u0e0c\u0e0d\u0e0e\u0e0f\u0e10\u0e11\u0e12\u0e13\u0e14\u0e15\u0e16\u0e17\u0e18\u0e19\u0e1a\u0e1b\u0e1c\u0e1d\u0e1e\u0e1f\u0e20\u0e21\u0e22\u0e23\u0e24\u0e25\u0e27\u0e28\u0e29\u0e2a\u0e2b\u0e2c\u0e2d\u0e2e": [
            "./extra/foo_dd.png",
            "content/sad/\u0e01\u0e02\u0e03\u0e04\u0e05\u0e06\u0e07\u0e08\u0e09\u0e0a\u0e0b\u0e0c\u0e0d\u0e0e\u0e0f\u0e10\u0e11\u0e12\u0e13\u0e14\u0e15\u0e16\u0e17\u0e18\u0e19\u0e1a\u0e1b\u0e1c\u0e1d\u0e1e\u0e1f\u0e20\u0e21\u0e22\u0e23\u0e24\u0e25\u0e27\u0e28\u0e29\u0e2a\u0e2b\u0e2c\u0e2d\u0e2e/dd/processed/re_OpMEkSwgjI_pr.png",
            "content/sad/\u0e01\u0e02\u0e03\u0e04\u0e05\u0e06\u0e07\u0e08\u0e09\u0e0a\u0e0b\u0e0c\u0e0d\u0e0e\u0e0f\u0e10\u0e11\u0e12\u0e13\u0e14\u0e15\u0e16\u0e17\u0e18\u0e19\u0e1a\u0e1b\u0e1c\u0e1d\u0e1e\u0e1f\u0e20\u0e21\u0e22\u0e23\u0e24\u0e25\u0e27\u0e28\u0e29\u0e2a\u0e2b\u0e2c\u0e2d\u0e2e/dd/processed/re_yJRzhvfbFD_pr.png",
            "./extra/ref_dd.png"
        ]
    },
    "sdf": {
        "q": [
            "./extra/ee.png",
            "content/sdf/q/ee/processed/re_NvkOuwSDlR_pr.png",
            "content/sdf/q/ee/processed/re_TCJVJxncXT_pr.png",
            "content/sdf/q/ee/processed/re_ZNboeXOrMc_pr.png",
            "content/sdf/q/ee/processed/re_dAjRYOFKgL_pr.png",
            "content/sdf/q/ee/processed/re_gMgEUbsITn_pr.png",
            "content/sdf/q/ee/processed/re_hXZKgMVsaD_pr.png",
            "content/sdf/q/ee/processed/re_jLafNgCXHH_pr.png",
            "./extra/foo_ee.png",
            "./extra/ref_ee.png"
        ]
    },
    "ssdsd": {
        "ss": [
            "./extra/asd.png",
            "content/ssdsd/ss/asd/processed/ed_GhpWeRmVPU_pr.png",
            "content/ssdsd/ss/asd/processed/ed_MZZIXoDXyq_pr.png",
            "content/ssdsd/ss/asd/processed/ed_PGdxcVDUyz_pr.png",
            "content/ssdsd/ss/asd/processed/ed_PPQzcyQdPY_pr.png",
            "content/ssdsd/ss/asd/processed/ed_QUVFNOFRue_pr.png",
            "content/ssdsd/ss/asd/processed/ed_SqHyyOgzod_pr.png",
            "content/ssdsd/ss/asd/processed/ed_SxPzNQoTEl_pr.png",
            "content/ssdsd/ss/asd/processed/ed_VpLiayYQdl_pr.png",
            "content/ssdsd/ss/asd/processed/ed_YTAACDsImA_pr.png",
            "content/ssdsd/ss/asd/processed/ed_hrnkeXyqPM_pr.png",
            "content/ssdsd/ss/asd/processed/ed_kuiYeZaWbc_pr.png",
            "content/ssdsd/ss/asd/processed/ed_tIXMBshNuS_pr.png",
            "content/ssdsd/ss/asd/processed/ed_wtoKpqivWV_pr.png",
            "./extra/foo_asd.png",
            "content/ssdsd/ss/asd/processed/1__yGrYVZrOIO_pr.png",
            "content/ssdsd/ss/asd/processed/2__uKGdbizZhc_pr.png",
            "content/ssdsd/ss/asd/processed/3__czgFzMwAQk_pr.png",
            "content/ssdsd/ss/asd/processed/4__SGogMgoybO_pr.png",
            "content/ssdsd/ss/asd/processed/5__VMOXTAHsID_pr.png",
            "content/ssdsd/ss/asd/processed/6__DNrhoPipbh_pr.png",
            "content/ssdsd/ss/asd/processed/7__sSWxrvXVUA_pr.png",
            "content/ssdsd/ss/asd/processed/8__ahEHNcTknR_pr.png",
            "content/ssdsd/ss/asd/processed/9__UOvPYKWdcO_pr.png",
            "content/ssdsd/ss/asd/processed/10_DFLgsXsATK_pr.png",
            "content/ssdsd/ss/asd/processed/11_eIEBrJvsiR_pr.png",
            "content/ssdsd/ss/asd/processed/12_wlAkWRLDkc_pr.png",
            "content/ssdsd/ss/asd/processed/13_fVmMISiNHj_pr.png",
            "./extra/ref_asd.png"
        ]
    },
    "test": {
        "ssdfdf": [
            "./extra/foo_ffs.png",
            "content/test/ssdfdf/ffs/processed/re_GMKCNwlBaZ_pr.png",
            "content/test/ssdfdf/ffs/processed/re_MyiMQHfCAU_pr.png",
            "content/test/ssdfdf/ffs/processed/re_RCVSXXgskL_pr.png",
            "content/test/ssdfdf/ffs/processed/re_XImgLrAOBu_pr.png",
            "content/test/ssdfdf/ffs/processed/re_bryqJTCDRW_pr.png",
            "content/test/ssdfdf/ffs/processed/re_rLRLOlPrnb_pr.png",
            "./extra/ref_ffs.png"
        ]
    }
}